services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: db
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: user
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - data:/data/db
      - ./init_db.js:/docker-entrypoint-initdb.d/init_db.js:ro
volumes:
  data:


