services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    ports:
      - 8080:8080
    environment:
      MONGODB_PRE: mongodb
      MONGODB_HOST: db
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: user
      AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      MESSAGING_SERVICE_SID: ${TWILIO_MESSAGING_SERVICE_SID}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: multipleCard
    volumes:
      - data:/data/db
      - ./init_db.js:/docker-entrypoint-initdb.d/init_db.js:ro
      - ./mongo-keyfile:/data/configdb/mongo-keyfile
    command: mongod --replSet repl --bind_ip_all --keyFile /data/configdb/mongo-keyfile
    ports:
      - 27018:27017
volumes:
  data:


